version: "3.1"

services:
  postgres:
    container_name: autumn-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autumn_postgres
    ports:
      - 5434:5432
    volumes:
    - ./create_tables.sql:/docker-entrypoint-initdb.d/init.sql
    - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
